Universidade Federal do Rio Grande do Sul (UFRGS)   
Programa de Pós-Graduação em Engenharia Civil (PPGEC)   


# Python aplicado à análise de estruturas
## Aula 3: Módulos Básicos - Parte 1

[1. Trabalhando com módulos](#section_1)

[2. NumPy ](#section_2)

[ 2.1. Criação de arrays ](#section_21)

[  2.1.1. np.array ](#section_211)

[  2.1.2. np.zeros ](#section_212)

[  2.1.3. np.ones ](#section_213)

[  2.1.4. np.eye ](#section_214)

[  2.1.5. np.diag ](#section_215)

[  2.1.6. np.linspace ](#section_216)

[  2.1.7. Outras formas ](#section_217)

[ 2.2. Manipulação de arrays ](#section_22)

[  2.2.1. Alteração de elemento ](#section_221)

[  2.2.2. Determinação do tamanho e forma ](#section_222)

[  2.2.3. Cópia de arrays ](#section_223)

[  2.2.4. Transposição de arrays ](#section_224)

[ 2.3. Operações e funções matemáticas ](#section_23)

[ 2.4. Algebra linear com arrays ](#section_24)

[3. SciPy ](#section_3)

[ 3.1. Determinação das raízes de uma função ](#section_31)

[ 3.2. Determinação de autovalores e autovetores ](#section_32)


---

_Eng. MSc Eduarto Pagnussat Titello_

_Eng. Daniel Barbosa M. Matos_

# Trabalhando com módulos <a name="section_1"></a>
Módulos são bibliotecas de funções e classes que podem ser facilmente importados e introduzem novas funcionalidades à linguagem. Os principáis módulos para aplicações científicas são:
- [NumPy](https://numpy.org/doc/stable/index.html) para operações matriciais;
- [SciPy](https://docs.scipy.org/doc/scipy/reference/) para cálculo numérico;
- [matplotlib](https://matplotlib.org/users/index.html) para plotagem de gráficos;
- [Pandas](https://pandas.pydata.org/docs/user_guide/index.html) para trabalho com séries de dados.

Além desses, diversos outros módulos criados pela comunidade estão disponíveis nos repositórios do [PyPi](https://pypi.org/) e do [Anaconda](https://anaconda.org/anaconda/repo). A criação de módulos pelo usuário pode ser realizada de forma simplificada inserindo todas as funções e variáveis de interesse em um arquivo `.py` (ou em uma pasta) no diretório de trabalho. 

A utilização de módulos requer sua importação através do comando `import`, o código a seguir realiza a importação do módulo `scipy` e solicita ao Python o tipo de `scipy`.

In [1]:
import scipy
print(type(scipy))

<class 'module'>


A importação de módulos pelo comando `import` mantem um vínculo entre o conteúdo importado e o nome do módulo, dessa forma todas suas funções devem ser chamadas na forma `modulo.funcao(...)` onde `funcao(...)` é a função de interesse que pertence ao módulo. 

A importação de módulos pode ainda ser realizada na forma "importar como", onde é criado um "apelido" para o módulo, através da sintaxe `import modulo as apelido`. A seguir é importado o módulo `numpy` com o "apelido" `np` e é printando o tipo de `np`.

In [2]:
import numpy as np
print(type(np))

<class 'module'>


Existem ainda módulos internos à outros módulos, sua importação é realizada na forma `import modulo.submodulo`. Um exemplo de submódulo é o `pyplot` que pertence ao módulo `matplotlib`, usualmente sua importação é realizada com o "apelido" `plt`, dessa forma:

In [3]:
import matplotlib.pyplot as plt

A importação de módulos pode ainda ser realizada sem a manutenção de vínculo entre o nome do módulo e a função através da sintaxe `from modulo import funcao`, entretanto tal prática não é recomendada na presença de diferentes módulos. 

# NumPy <a name="section_2"></a>
O NumPy é o principal módulo para operação de matrizes e similares em Python. Sua base são arrays representadas através do objeto `ndarray` que é basicamente uma tabela de dimensão `n`, podendo assim representar escalares, vetores, matrizes e outros elementos de ordem superior.

Usualmente o NumPy é importado como `np`, conforme realizado anteriormente (`import numpy as np`).

## Criação de arrays <a name="section_21"><a>
    
Arrays do NumPy podem ser criadas de diversas maneiras. 

### np.array <a name="section_211"><a>
    
Arrays podem ser criadas a partir de listas e tuplas com a função `np.array(lista)`. Ao passar uma lista de valores para a função um vetor é gerado, uma lista de listas produz uma matriz e etc.  

Como exemplo vamos criar e printar 3 listas: `l1`, `l2` e `l3`, onde `l3` é uma lista de listas formada pelas outras duas.

In [6]:
l1 = [1,3,5]
l2 = [20,30,40]
l3 = [l1, l2]

print('l1:', l1)
print('l2:', l2)
print('l3:', l3)

l1: [1, 3, 5]
l2: [20, 30, 40]
l3: [[1, 3, 5], [20, 30, 40]]


Tranformando as três listas em arrays temos 2 vetores (`v1` e `v2`) e uma matriz (`m1`):

In [7]:
v1 = np.array(l1)
v2 = np.array(l2)
m1 = np.array(l3)

print('v1:\n', v1)
print('v2:\n', v2)
print('m1:\n', m1)

v1:
 [1 3 5]
v2:
 [20 30 40]
m1:
 [[ 1  3  5]
 [20 30 40]]


Os termos dos vetores e da matriz gerada podem ser acessados como os itens de listas, tuplas e dicionários:

In [8]:
print('Primeiro termo de v2:', v2[0])
print('Último termo da segunda linha de m1:', m1[1,-1])

Primeiro termo de v2: 20
Último termo da segunda linha de m1: 40


Linhas e colunas inteiras ou parte dessas também podem ser acessadss:

In [9]:
print('Primeira linha completa de m1:', m1[0,:])
print('Última coluna de m1:', m1[:,2])

Primeira linha completa de m1: [1 3 5]
Última coluna de m1: [ 5 40]


### np.zeros <a name="section_212"><a>
Arrays de zeros podem ser criadas através da função `np.zeros(dims)` fornecendo as dimensões desejadas em uma lista ou tupla de dimensões, por exemplo:

Para um vetor de tamanho 5:

In [11]:
v_zeros1 = np.zeros([5])
print(v_zeros1)

[0. 0. 0. 0. 0.]


Para uma matriz de 3 linhas 4 colunas:

In [13]:
m_zeros1 = np.zeros([3,4])
print(m_zeros1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### np.ones <a name="section_213"><a>
Arrays unitários podem ser criados através da função `np.ones(dims)` forncendo as dimensões como em `np.zeros(dims)`.

Para uma matriz 3x4:

In [14]:
m_ones1 = np.ones((3,4))
print(m_ones1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Essa função pode ser usada para outros valores, como um vetor onde todos termos são 25:

In [16]:
v_25s = 25*np.ones((6))
print(v_25s)

[25. 25. 25. 25. 25. 25.]


### np.eye <a name="section_214"><a>

Matrizes identidade podem ser criadas através da funcão `np.eye(dim1,dim2)` passando as dimensões da matriz, caso apenas uma dimensão seja informada será gerada uma matriz quadrada. 

Para gerar uma matriz identidade 4x4:

In [39]:
m_id4 = np.eye(4)
print(m_id4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Para uma matriz identidade 3x6

In [40]:
m_id46 = np.eye(4,6)
print(m_id46)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


### np.diag <a name="section_215"><a>
A função `np.diag(array)` ao receber uma matriz como entrada retorna um vetor com os termos da sua diagonal, o inverso também é valido, ao receber um vetor a função retorna uma matriz com os termos do vetor na diagonal. 

Criando uma matriz 3x3 e extraindo sua diagoal:

In [17]:
m3 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
diag = np.diag(m3)
print(diag)

[1 5 9]


Ok! A função retornou os termos da diagonal, vamos agora construir uma matriz com base nesse vetor:

In [19]:
m4 = np.diag(diag)
print(m4)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


A matriz gerada contem apenas termos na diagonal.

### np.linspace <a name="section_216"><a>
A função `np.linspace(inicio, fim, nptos)` cria um vetor de `nptos` igualmente espaçados no intervalo `[inicio, fim]`. 

Criando 10 valores de 1 a 10:

In [43]:
v1_10 = np.linspace(1, 10, 10)
print(v1_10)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Criando 12 valores entre 5 e 40:

In [44]:
v5_40 = np.linspace(5, 40, 12)
print(v5_40)

[ 5.          8.18181818 11.36363636 14.54545455 17.72727273 20.90909091
 24.09090909 27.27272727 30.45454545 33.63636364 36.81818182 40.        ]


### Outras formas <a name="section_217"><a>
Existem ainda diversas outras funções para criação de arrays no NumPy, essas podem ser acessadas [aqui](https://numpy.org/doc/stable/reference/routines.array-creation.html).

## Manipulação de arrays <a name='section_3'></a>
Arrays podem ser modificadas, empilhadas, operadas matricialmente e etc.

### Alteração de elemento <a name='section_31'></a>
A alteração de um elemento de um array pode ser realizada como a alteração de um elemento de uma lista. Adotando a matriz diagonal `m4` criada anteriormente podemos alterar o termo da terceira coluna e primeira linha por:

In [45]:
m4[0, 2] = 99
print(m4)

[[ 1  0 99]
 [ 0  5  0]
 [ 0  0  9]]


lembrando que os índices em Python iniciam em `0`, dessa forma a primeira linha é a linha `0` e a terceira coluna é a coluna `2`.

Toda uma linha ou coluna pode ser alterada, usando `:` para sinalizar todos seus elementos. A seguir vamos definir todos elementos da primeira coluna de `m4` como `-1`. 

In [46]:
m4[:,0] = -1
print(m4)

[[-1  0 99]
 [-1  5  0]
 [-1  0  9]]


### Determinação do tamanho e forma <a name='section_32'></a>
O tamanho e a forma de arrays podem ser determinados pelos comandos `size` e `shape`, respectivamente, onde ambos podem ser acessados tanto através da biblioteca principal (`np.size(array)` e `np.shape(array)`) como através do próprio elemento (`array.size`, `array.shape`), onde `array` é uma array genérica. Adotando a array `m4` vamos plotar sua forma e tamanho pelos dois métodos apresentados:

In [20]:
print('Forma de m4')
print(np.shape(m4))
print(m4.shape)
print('Tamanho de m4')
print(np.size(m4))
print(m4.size)

Forma de m4
(3, 3)
(3, 3)
Tamanho de m4
9
9


Como resultado para a forma de `m4` obtivemos `(3,3)`, o que significa que a array `m4` tem 3 linhas e 3 colunas. Já o tamanho de `m4` encontrado é `9`, ou seja, `m4` tem 9 elementos (`3x3=9`). Vamos printar agora os tamanhos e formas de outros vetores e matrizes:

In [48]:
print('Forma e tamanho de m_id46')
print(m_id46.size)
print(m_id46.shape)

print('Forma e tamanho de v1_10')
print(v1_10.size)
print(v1_10.shape)

Forma e tamanho de m_id46
24
(4, 6)
Forma e tamanho de v1_10
10
(10,)


### Cópia de arrays <a name='section_33'></a>
A realização de cópias de arrays deve ser feita através do comando `np.copy()` ou do método `array.copy()`, visto que uma simples atribuição `arrayA=arrayB` faz uma conexão de memória que poderá ocasionar em erros futuros.

In [49]:
print('m4 original:\n', m4)
A = m4
B = m4.copy() #ou B=np.copy(m4)
A[1,1] = 666
B[1,1] = 999
print('m4:\n', m4)
print('A:\n', A)
print('B:\n', B)

m4 original:
 [[-1  0 99]
 [-1  5  0]
 [-1  0  9]]
m4:
 [[ -1   0  99]
 [ -1 666   0]
 [ -1   0   9]]
A:
 [[ -1   0  99]
 [ -1 666   0]
 [ -1   0   9]]
B:
 [[ -1   0  99]
 [ -1 999   0]
 [ -1   0   9]]


In [50]:
print(A is m4)
print(B is m4)

True
False


### Transposição de arrays <a name='section_34'></a>
O transposto de uma array é obtida adicionando `.T` à sua chamada. No caso de vetores o resultado é indiferente. Como exemplo vamos transpor a matriz `m_id46` e o vetor `v1_10`. 

In [79]:
print(m_id46.shape)
print(m_id46.T.shape)

print(v1_10.shape)
print(v1_10.T.shape)

(4, 6)
(6, 4)
(10,)
(10,)


## Operações e funções matemáticas <a name='section_23'></a>

O módulo Numpy possui uma série de funções e constantes matemáticas, como:

* np.exp(): função exponencial;

* np.sin(), np.cos(), np.tan(), etc : funções trigonométricas;

* np.sqrt() : realiza a raiz quadrada;

* np.pi: $\pi$;

* np.log(): logarítmo natural;

* np.log10(): logarítmo na base 10.

Diferentemente das listas, as arrays do NumPy são operadas termo a termo, dessa forma as funções anteriores possuem a mesma propriedade. Vamos então ilustrar calculando a expressão a seguir para valores de x de 0 à 10. $$y(x) = \exp^{5x-10}\sin(3\pi+\sqrt{4x})$$

In [21]:
x = np.linspace(0,10,41) # 41 valores resulta em valores a cada 0.25
print(x)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.    2.25  2.5   2.75
  3.    3.25  3.5   3.75  4.    4.25  4.5   4.75  5.    5.25  5.5   5.75
  6.    6.25  6.5   6.75  7.    7.25  7.5   7.75  8.    8.25  8.5   8.75
  9.    9.25  9.5   9.75 10.  ]


In [69]:
y = np.exp(+5*x-10)*np.sin(3*np.pi+np.sqrt(4*x))
print(y)

[ 1.66796636e-20 -1.33340607e-04 -5.46317906e-04 -1.90540967e-03
 -6.12679787e-03 -1.85025661e-02 -5.23831686e-02 -1.36310914e-01
 -3.08071742e-01 -4.92557226e-01  2.51976998e-01  7.40461201e+00
  4.70391298e+01  2.31806467e+02  1.02099414e+03  4.21494202e+03
  1.66696843e+04  6.39132894e+04  2.39271597e+05  8.78680102e+05
  3.17512400e+06  1.13139890e+07  3.98151706e+07  1.38518524e+08
  4.76743911e+08  1.62383558e+09  5.47423593e+09  1.82625012e+10
  6.02643613e+10  1.96557493e+11  6.32895323e+11  2.00829404e+12
  6.26415699e+12  1.91329134e+13  5.68889302e+13  1.63091288e+14
  4.43156739e+14  1.10207358e+15  2.28945992e+15  2.57468835e+15
 -9.73511413e+15]


## Algebra linear com arrays <a name='section_24'></a>

Arrays podem representar vetores e matrizes, todavia a multiplicação de uma array `x` por ela mesma `x*x` resulta em uma operação termo a termo. A multiplicação matricial da array `x` por ela mesma é realizada pela função `np.dot(x,x)` ou `x.dot(x)`. Cabe lembrar que no caso de matrizes o número de colunas de primeira matriz (`n x j`) deve ser igual o número de linhas da segunda matriz (`j x m`), que podem ser acessados por `np.shape()`, resultando em uma matriz `n x m`. Já no caso de vetores esses devem ter o mesmo comprimento, não havendo diferença entre vetores linha e vetores coluna. 

Adotando duas matrizes `X1(4,2)` e `X2(2,6)` temos que:

In [45]:
np.random.seed(8198916)
X1 = np.random.randint(0, 10, (4,2)) # Gera número inteiros aleatórios entre 0 e 10
X2 = np.random.randint(0, 10, (2,4))
print('X1:\n', X1)
print('X2:\n', X2)

X3 = X1.dot(X2)
print('X3:\n', X3)

X1:
 [[7 8]
 [9 4]
 [0 2]
 [0 7]]
X2:
 [[6 9 6 1]
 [7 2 4 9]]
X3:
 [[98 79 74 79]
 [82 89 70 45]
 [14  4  8 18]
 [49 14 28 63]]


O submódulo `numpy.linalg` oferece várias operações matriciais, como a inversão da matriz (`np.linalg.inv(array)`) e o cálculo do determinante (`np.linalg.det(array)`). 

In [46]:
print(np.linalg.inv(X3))
print(np.linalg.det(X3))

[[ 1.22583439e+14 -9.53426749e+13  3.96446149e+13 -9.69408634e+13]
 [-4.03602217e+13  3.13912835e+13  1.09115720e+15 -2.83571108e+14]
 [-5.14592826e+13  4.00238865e+13 -1.76129431e+15  5.39166763e+14]
 [-6.35029445e+13  4.93911791e+13  5.09483394e+14 -1.01215421e+14]]
-2.3271643223052853e-26


É possível, também, solucionar sistemas pela forma matricial, sendo necessário apenas o conhecimento da matriz de coeficientes e o vetor resposta. Vamos utilizar o exemplo abaixo:
\begin{align}
\begin{bmatrix}
5&2&1\\
2&5&2\\
3&-2&4
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
=
\begin{bmatrix}
63\\
18\\
11
\end{bmatrix}
\end{align} 

Utilizando a função `np.linalg.solve(A, b)`, é possível solucionar o sistema.

In [53]:
A = np.array([[5, 2, 18],
              [2, 5, 2],
              [3,-2, 4]])

b = np.array([63, 18, 11])

x = np.linalg.solve(A, b)
print(x)

[1. 2. 3.]


# SciPy <a name="section_3"></a>

A Scipy é um módulo eficiente para a realização de procedimentos numéricos, como integração numérica, interpolação, otimização, problemas da algebra linear e problemas de estatística. O módulo pode ser importando por `import scipy as sc`.


In [55]:
import scipy as sc
import scipy.optimize as opt
import scipy.linalg as lin

## Determinação das raízes de uma função <a name="section_31"></a>

Para determinar a raiz de uma função pelo método de Newton-Raphson, utiliza-se a função `sc.optimize.newton()`.

In [64]:
def func(x, a, b, c):
    return a*x**2 + b*x + c
res = opt.newton(func, args=[-1, 2, 3], x0=0)
print(res)

-1.0000000000000004


## Determinação de autovalores e autovetores <a name="section_32"></a>

Para determinar os autovalores e autovetores de uma matriz é utilizada a função `scipy.linalg.eig(array)`. Essa função retorna 2 arrays, o primeiro contendo o vetor de autovalores e o segundo a matriz de autovetores, denominados no exemplo a seguir como `w` e `phi`.

In [67]:
w, phi = lin.eig(X3)

# Garantindo que os autovetores e autovalores estejam em ordem crescente
iw = w.argsort()                     
w  = w[iw]
phi = phi[:, iw]
print(phi)
print(w)

[[-0.78895194 -0.38560276 -0.12196812 -0.70612365]
 [ 0.37413673 -0.31857084 -0.7338288  -0.63176069]
 [ 0.15047878  0.86580853  0.18359493 -0.087854  ]
 [ 0.46360833 -0.01409701  0.64258227 -0.30748901]]
[-1.45112789e-14+0.j -6.96947394e-17+0.j  4.57113453e+01+0.j
  2.12288655e+02+0.j]
