Vamos começar criando uma matriz `a` 4x4 onde os elementos são `ij` (linha `i`, coluna `j`)

In [1]:
import numpy as np
a = np.array([[ 0, 1, 2, 3],
              [10,11,12,13],
              [20,21,22,23],
              [30,31,32,33]])
print(a)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Chamando `a` por apenas um elemento recebemos toda a linha que foi informada:

In [2]:
a[0]

array([0, 1, 2, 3])

Passando dois valores recebemos o valor na respectiva linha e coluna:

In [3]:
a[1,2]

12

Mas ainda podemos passar listas de elementos, como uma lista de linhas:

In [4]:
a[[0,2]]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23]])

Ok, recebemos as linhas que informamos completas. 

Vamos agora passar uma lista de linhas e uma lista de colunas:

In [5]:
a[[0,2], [1,3]]

array([ 1, 23])

Como retorno recebemos os elementos `[0,1]` e `[2,3]`, ou seja, as linhas e colunas foram relacionadas pelos índices das listas. Semelhante ao que teriamos plotando um gráfico 2D, para cada `x(i)` temos um único `y(i)`. 

No nosso caso temos algo semelhante à um gráfico 3D, onde `x` e `y` são as linhas e colunas da matriz, enquanto `z(x,y)` é o elemento `[x,y]`. Para aplicarmos isso nos índices dos arrays precisamos ter então **listas em dimensões diferentes (arrays 2D)**. 

Vamos posicionar nossas linhas em uma lista vertical de linhas (tudo em uma única coluna):

In [6]:
linhas = np.array([[0,2,3]]).T # Cria tudo na mesma linha e já transpõe antes de armazenar
print(linhas)

[[0]
 [2]
 [3]]


Enquanto nossas colunas de interesse serão armazenadas em um array horizontal de colunas (tudo em única linha):

In [7]:
colunas = np.array([[1,3]])
print(colunas)

[[1 3]]


Dessa forma, quando passarmos as variáveis `linhas` e `colunas` como índices do nosso array, cada linha de `linhas` será combinada com todas as colunas `colunas` (que só tem uma linha). Com isso conseguimos acessar apenas elementos que combinam a linha `x` com a coluna `y`:

In [8]:
print(a[linhas, colunas])

[[ 1  3]
 [21 23]
 [31 33]]


Ok, funciona! Extraímos apenas os elementos solicitados de `a`.

A resposta obviamente tem o número de linhas e colunas solicitado anteriormente, dessa forma podemos substituir essa parte da matriz `a` por uma matriz do tamanho dessa seção, como por exemplo:

In [9]:
a[linhas, colunas] = np.array([[-1,-3],
                               [-221,-223],
                               [-331,-333]])

print(a)

[[   0   -1    2   -3]
 [  10   11   12   13]
 [  20 -221   22 -223]
 [  30 -331   32 -333]]


Podemos ver que toda a linha 1 e as colunas 0 e 2 mantem seus valores originais, enquanto os demais são os definidos no código anterior.